### ISSUE TITLE
Double-check my video summaries.

### ISSUE THREAD

**Issue by 1point618** [1point618/curriculum-github#2]
I've made a list of "salient points from each video" under the file `./plaintext documents/videos.md`. I'd love if folks could take a look at them and make sure I haven't made any clear mistakes. No need to watch the videos, just make sure that I didn't generalize something such that it turned out wrong.

**Comment by rhoboat** [comment]
> 5.7 When performing a merge, you need to be checked out into the branch you are merging into

would it be clearer to say
`When performing a merge, you need to have checked out the branch you are merging into`

**Comment by rhoboat** [comment]
in 5.7

> To send the merge to the remote, simply git push. This will open and execute a pull request on GitHub. 

I'm not aware of this. I thought pushing a merge closes a pull request for that branch if one has been opened. But I'm not aware of how to open a PR from the command line, unless you use the Hub tool.

**Comment by rhoboat** [comment]
6.12, there's a typo

> The command git commit --ammend will add whatever is in your staging area to your last commit, and allow you to edit that commit message.

`amend`

**Comment by rhoboat** [comment]
6.16 typo

> git restet HEAD <file_name> will remove a file from the staging area, putting it back in your working directory.

`reset`

**Comment by rhoboat** [comment]
6.22 typo

> git checkout -- <file_name> is the syntax. The -- lets git know you're talkind about a file. This will revert the file to the version found in the last commit.

`talking`

**Comment by rhoboat** [comment]
6.22 and 6.24, you use "staged" and "staging" I wonder if anyone will think those are referring two different things.
